# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      #- uses: r-lib/actions/setup-pandoc@v2

      #- uses: r-lib/actions/setup-r@v2
      #  with:
      #    use-public-rspm: true

      #- uses: r-lib/actions/setup-r-dependencies@v2
      #  with:
      #    extra-packages: any::pkgdown, local::., airway, org.Hs.eg.db, clusterProfiler, DEGreport
      #    needs: website

      - name: install miniforge
        run: |
          wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3.sh -b -p "${HOME}/conda"
          echo "^Miniforge3\.sh$" >> .Rbuildignore


      - name: conda env
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda config --add channels conda-forge
          conda config --set channel_priority strict

          # make the env one above WORKDIR
          conda env create -p ../env --file pkgdown-requirements.yaml

      - name: Build site
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate ../env

          Rscript -e "setRepositories(ind=1:5); remotes::install_github('NICHD-BSPC/carnation@r4.3', upgrade='never')"
          Rscript -e "pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)"

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
